# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   host: localhost

# development:
#   <<: *default
#   database: TBL_development
# test:
#   <<: *default
#   database: TBL_test

# production:
#   <<: *default
#   database: TBL_production
#   username: TBL
#   password: <%= ENV['TBL_DATABASE_PASSWORD'] %>

# SQLite. Versions 3.8.0 and up are supported.
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
